// Generates src/domain/generated/kyc-enums.ts from the C# enums in kycanalyzer-nuget.
//
// The generated file is committed. This script only needs to run when the enums change,
// so the app still builds in an environment where the source repo is unavailable.
//
//   node scripts/gen-enums.mjs [path-to-kycanalyzer-nuget]

import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const appRoot = resolve(here, '..');

const nugetRoot = resolve(
  process.argv[2] ?? join(appRoot, '../../../../kycanalyzer-nuget'),
);
const enumDir = join(nugetRoot, 'eToro.KYCAnalyzerService.Enums');

const SOURCES = [
  { file: join(enumDir, 'ClientRiskProfile/KycQuestion.cs'), name: 'KycQuestion' },
  { file: join(enumDir, 'ClientRiskProfile/KycAnswer.cs'), name: 'KycAnswer' },
  { file: join(enumDir, 'Regulation.cs'), name: 'Regulation' },
  { file: join(enumDir, 'ClientRiskProfile/RiskLevel.cs'), name: 'RiskLevel' },
  { file: join(enumDir, 'ClientRiskProfile/BlockResult.cs'), name: 'BlockResult' },
  { file: join(enumDir, 'ClientRiskProfile/RecalculationReason.cs'), name: 'RecalculationReason' },
];

/**
 * C# allows implicit values (`Foo,` continues from the previous member), so track
 * the running value rather than requiring an `=` on every line.
 */
function parseEnum(source, enumName) {
  const body = source
    .replace(/\/\/[^\n]*/g, '')
    .replace(/\/\*[\s\S]*?\*\//g, '');

  const start = body.search(new RegExp(`enum\\s+${enumName}\\b`));
  if (start === -1) throw new Error(`enum ${enumName} not found`);

  const open = body.indexOf('{', start);
  const close = body.indexOf('}', open);
  const members = [];
  let next = 0;

  for (const raw of body.slice(open + 1, close).split(',')) {
    const line = raw.trim();
    if (!line) continue;
    const m = /^([A-Za-z_]\w*)\s*(?:=\s*(-?\d+))?$/.exec(line);
    if (!m) throw new Error(`${enumName}: cannot parse member "${line}"`);
    const value = m[2] === undefined ? next : Number(m[2]);
    members.push([m[1], value]);
    next = value + 1;
  }

  return members;
}

/**
 * Several C# members can share one value, so the id -> name direction is genuinely
 * ambiguous. Emitting them as duplicate object keys is both a type error and a silent
 * last-one-wins, so instead: the first declaration becomes canonical, and every colliding
 * group is emitted separately so the UI can disclose the ambiguity rather than hide it.
 */
function splitAliases(members, enumName) {
  const canonical = new Map();
  const groups = new Map();

  for (const [name, value] of members) {
    if (!canonical.has(value)) canonical.set(value, name);
    const group = groups.get(value) ?? [];
    group.push(name);
    groups.set(value, group);
  }

  const aliases = [...groups.entries()].filter(([, names]) => names.length > 1);
  for (const [value, names] of aliases) {
    console.warn(`  ! ${enumName}: value ${value} shared by ${names.join(', ')}`);
  }

  return { canonical, aliases };
}

const blocks = [];
const summary = [];

for (const { file, name } of SOURCES) {
  if (!existsSync(file)) {
    console.warn(`  ! skipped ${name} — ${file} not found`);
    continue;
  }
  const members = parseEnum(readFileSync(file, 'utf8'), name);
  const { canonical, aliases } = splitAliases(members, name);
  summary.push(`${name} (${members.length}${aliases.length ? `, ${aliases.length} aliased` : ''})`);

  const names = [...canonical.entries()].map(([v, n]) => `  ${v}: '${n}',`).join('\n');
  const ids = members.map(([n, v]) => `  ${n}: ${v},`).join('\n');
  const aliasEntries = aliases
    .map(([v, group]) => `  ${v}: [${group.map((n) => `'${n}'`).join(', ')}],`)
    .join('\n');

  blocks.push(
    `/** Id -> canonical (first-declared) name. */\n` +
      `export const ${name}Names: Readonly<Record<number, string>> = {\n${names}\n};\n\n` +
      `/** Name -> id. Every member, including aliases. */\n` +
      `export const ${name}Ids: Readonly<Record<string, number>> = {\n${ids}\n};\n\n` +
      `/** Ids with more than one member name, so callers can disclose the ambiguity. */\n` +
      `export const ${name}Aliases: Readonly<Record<number, readonly string[]>> = {\n${aliasEntries}\n};`,
  );
}

const out = join(appRoot, 'src/domain/generated/kyc-enums.ts');
mkdirSync(dirname(out), { recursive: true });
writeFileSync(
  out,
  [
    '// GENERATED by scripts/gen-enums.mjs — do not edit by hand.',
    `// Source: kycanalyzer-nuget/eToro.KYCAnalyzerService.Enums`,
    '',
    ...blocks,
    '',
  ].join('\n'),
);

console.log(`wrote ${out}`);
console.log(`  ${summary.join(', ')}`);
